# Generated by Django 5.2.1 on 2026-02-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idcourse', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstname', max_length=45)),
                ('lastName', models.CharField(db_column='lastname', max_length=45)),
                ('department', models.CharField(max_length=20)),
                ('degree', models.CharField(choices=[('MS', 'Master of Science'), ('PhD', 'Doctor of Philosophy')], max_length=3)),
                ('resume', models.BinaryField()),
                ('teachingExperienceBool', models.CharField(db_column='teachingexperiencebool', max_length=45)),
                ('teachingExperienceText', models.CharField(db_column='teachingexperiencetext', max_length=250)),
                ('campus', models.CharField(choices=[('Indy', 'Indianapolis'), ('WL', 'West Lafayette')], max_length=5)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('email', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstname', max_length=45)),
                ('lastName', models.CharField(db_column='lastname', max_length=45)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(db_column='categoryname', max_length=100)),
                ('knowledgeLevel', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], db_column='knowledgelevel')),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'db_table': 'knowledgecategory',
            },
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
        migrations.CreateModel(
            name='CourseInstructorYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.instructor')),
            ],
            options={
                'verbose_name': 'Course Instructor Year',
                'verbose_name_plural': 'Course Instructor Years',
                'db_table': 'courseinstructoryear',
            },
        ),
        migrations.CreateModel(
            name='CourseMustKnow',
            fields=[
                ('courseID', models.ForeignKey(db_column='courseid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='src.course')),
                ('categoryID', models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.CASCADE, to='src.knowledgecategory')),
            ],
            options={
                'verbose_name': 'Course Must Know',
                'verbose_name_plural': 'Course Must Knows',
                'db_table': 'coursemustknow',
            },
        ),
        migrations.CreateModel(
            name='CourseStudentYearKnowledge',
            fields=[
                ('studentID', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='src.student')),
                ('year', models.CharField(max_length=15)),
                ('level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('courseTaken', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_column='coursetaken', max_length=3)),
                ('knowledgeLevel', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], db_column='knowledgelevel')),
                ('catID', models.ForeignKey(db_column='catid', on_delete=django.db.models.deletion.CASCADE, to='src.knowledgecategory')),
                ('courseID', models.ForeignKey(db_column='courseid', on_delete=django.db.models.deletion.CASCADE, to='src.course')),
            ],
            options={
                'verbose_name': 'Course Student Year Knowledge',
                'verbose_name_plural': 'Course Student Year Knowledges',
                'db_table': 'coursestudentyearknowledge',
            },
        ),
    ]
