# Generated by Django 5.2.1 on 2026-02-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_course_student_instructor_knowledgecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudentyearknowledge',
            name='studentID',
            field=models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to='src.student'),
        ),
        migrations.AddField(
            model_name='coursestudentyearknowledge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudentyearknowledge',
            unique_together={('studentID', 'courseID', 'year', 'catID')},
        ),
    ]
